export const subject_role_enum = [
    { value: 'AAS', text: 'Personale di assistenza ad alta specializzazione' },
    { value: 'APR', text: 'Medico Medicina Generale Pediatra di Libera Scelta' },
    { value: 'PSS', text: 'Professionista del sociale' },
    { value: 'INF', text: 'Personale infermieristico' },
    { value: 'FAR', text: 'Farmacista' },
    { value: 'DSA', text: 'Direttore sanitario' },
    { value: 'DAM', text: 'Direttore amministrativo' },
    { value: 'OAM', text: 'Operatore amministrativo' },
    { value: 'ASS', text: 'Assistito' },
    { value: 'TUT', text: 'Tutore' },
    { value: 'ING', text: 'Informal giver (Assistito)' },
    { value: 'GEN', text: 'Genitore Assistito' },
    { value: 'NOR', text: 'Nodo regionale' },
    { value: 'DRS', text: 'Dirigente sanitario' },
    { value: 'RSA', text: 'Medico RSA' },
    { value: 'MRP', text: 'Medico Rete di Patologia' },
    { value: 'INI', text: 'Infrastruttura Nazionale per l’Interoperabilità' },
    { value: 'OGC', text: 'Operatore per la gestione dei consensi' },
    { value: 'OPI', text: 'Operatore di informativa' },
    { value: 'MDS', text: 'Ruolo del Ministero della Salute per la gestione del DGC' }
];