export const subj_app_id = [
    { value: '010', text: 'Regione Piemonte' },
    { value: '020', text: 'Regione Valle dAosta' },
    { value: '030', text: 'Regione Lombardia' },
    { value: '041', text: 'P.A. Bolzano' },
    { value: '042', text: 'P.A. Trento' },
    { value: '050', text: 'Regione Veneto' },
    { value: '060', text: 'Regione Friuli Venezia Giulia' },
    { value: '070', text: 'Regione Liguria' },
    { value: '080', text: 'Regione Emilia-Romagna' },
    { value: '090', text: 'Regione Toscana' },
    { value: '100', text: 'Regione Umbria' },
    { value: '110', text: 'Regione Marche' },
    { value: '120', text: 'Regione Lazio' },
    { value: '130', text: 'Regione Abruzzo' },
    { value: '140', text: 'Regione Molise' },
    { value: '150', text: 'Regione Campania' },
    { value: '160', text: 'Regione Puglia' },
    { value: '170', text: 'Regione Basilicata' },
    { value: '180', text: 'Regione Calabria' },
    { value: '190', text: 'Regione Sicilia' },
    { value: '200', text: 'Regione Sardegna' },
    { value: '000', text: 'INI' },
    { value: '001', text: 'SASN' },
    { value: '999', text: 'MDS' }
];
